language: php

php:
  - 5.6

env:
  - TESTER_PHP_BIN="php-cgi"

matrix:
  allow_failures:
    - php: hhvm

services:
  - mysql

before_install:
  - composer self-update -q

before_script:
  - cp app/config/sample.config.local.neon app/config/config.local.neon
  - cp app/config/config.travis.neon app/config/config.test.neon

install:
  - git config --global url."https://".insteadOf git://
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s ./tests/

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
