language: php

php:
  - 5.5

env:
  - TESTER_PHP_BIN="php-cgi"

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "$PUBLIC_SSH_KEY" > ~/.ssh/id_rsa.pub
  - echo -e "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa*
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

#before_script:
#  - mysql -u root -e 'CREATE DATABASE testbase;'
#  - mysql -u root testbase < tests/testbase.sql

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s ./tests/
  # - ./vendor/bin/tester -p $TESTER_PHP_BIN -c ./tests/php.ini -s ./tests/

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done