language: php

php:
  - 5.5

env:
  - TESTER_PHP_BIN="php-cgi"

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update -q
  - composer config github-oauth.github.com "${GH_TOKEN}"

before_script:
  - echo -e "${CONFIG_LOCAL}" > app/config/config.local.neon

install:
  - composer install --no-interaction --prefer-source

#before_script:
#  - mysql -u root -e 'CREATE DATABASE testbase;'
#  - mysql -u root testbase < tests/testbase.sql

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s ./tests/
  # - ./vendor/bin/tester -p $TESTER_PHP_BIN -c ./tests/php.ini -s ./tests/

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
