version: '2'
services:
  bigbandbiskupska:
    build: docker
    ports:
      - "8000:80"
    volumes:
      - ".:/app"
  mysql-master:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root